### ISSUE TITLE
[Quail] No protocol specified.

### ISSUE THREAD

**Issue by kaushikcfd** [illinois-scicomp/machine-shop-maintenance#10]
Binaries compiled with mpicc emits a "No protocal specified" message to `stderr`.

Steps to reproduce:
```
kgk2@quail:~/temp$ cat hello.c
#include <stdio.h>

int main() {
  printf("Hello World!\n");
  return 0;
}

kgk2@quail:~/temp$ /usr/bin/mpicc hello.c
kgk2@quail:~/temp$ /usr/bin/mpirun -np 1 ./a.out 
No protocol specified
Hello World!
kgk2@quail:~/temp$ 
```

**Comment by inducer** [comment]
Quail is super behind in updates after being down for a long time. The updates are running now. I'll let you know when they're done. Try again then. (Headed to bed soon, don't hold your breath. :)

**Comment by kaushikcfd** [comment]
Thank you! (yes, no hurries!)

**Comment by inducer** [comment]
Looks like the updates haven't done much. Since things seem to work OK aside from the extra message, I'm not sure I'll dig much deeper. If you do, let me know what you find.

**Comment by kaushikcfd** [comment]
Probably related to the graphical daemon?

On porter:
```
kgk2@porter:~$ systemctl -l | grep lightdm
kgk2@porter:~$ 
```

On quail:
```
kgk2@quail:~$ systemctl -l | grep lightdm
  session-c1.scope                                                                          loaded active running   Session c1 of user lightdm                                                  
  lightdm.service                                                                           loaded active running   Light Display Manager 
```

And [this SO thread](https://stackoverflow.com/questions/62881568/run-mpi-program-without-a-x11-server) happens to link the message to lightdm.

**Comment by kaushikcfd** [comment]
Workaround: using `OpenMPI 3.0.6` or `/usr/bin/mpiexec.mpich` gets rid of the noisy message.

**Comment by inducer** [comment]
Thanks for digging into this. I've removed lightdm (and hence the ability to use a GUI login) from quail for the moment. (@lukeolson, `apt install task-desktop-xfce` will put it back) Closing for now, let me know if that didn't help, and we'll reopen.
