### ISSUE TITLE
`time` package missing

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-scicomp/machine-shop-maintenance#54]
The `time` shell builtin isn't always sufficient, e.g.:

```bash
# works fine:
$ time true

real	0m0.000s
user	0m0.000s
sys	0m0.000s

# but doesn't work with setting a shell variable:
$ FOO=bar time true
-bash: time: command not found
```

**Comment by inducer** [comment]
FWIW, that commit on its own does nothing. To explain how that becomes reality: someone runs
```
shoprun /shared/config/update.sh
```
and that makes those changes reality.

(I've just added the `shoprun` script in d5a9d81.)

**Comment by inducer** [comment]
Not yet done, fixing some `apt` snag that some machines have hit.

**Comment by inducer** [comment]
Should be all good now.

**Comment by matthiasdiener** [comment]
> Should be all good now.

Thank you!
