### ISSUE TITLE
Suggestion: add `gh` package

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-scicomp/machine-shop-maintenance#58]
(I'm happy to do it if it is considered interesting)

**Comment by lukeolson** [comment]
Sounds good to me.  Just add a few lines here  https://github.com/illinois-scicomp/machine-shop-maintenance/blob/main/update.sh

**Comment by inducer** [comment]
Looks like this was done in bb8248dd76e65549cdb79aba9ba8146871e85a5c.

@matthiasdiener What procedure did you use to apply these changes? (There is one!)

**Comment by matthiasdiener** [comment]
> Looks like this was done in [bb8248d](https://github.com/illinois-scicomp/machine-shop-maintenance/commit/bb8248dd76e65549cdb79aba9ba8146871e85a5c).
> 
> @matthiasdiener What procedure did you use to apply these changes? (There is one!)

I haven't applied these yet aside from committing https://github.com/illinois-scicomp/machine-shop-maintenance/commit/bb8248dd76e65549cdb79aba9ba8146871e85a5c. I only found https://github.com/illinois-scicomp/machine-shop-maintenance/issues/54#issuecomment-1024753762 regarding a procedure to apply these changes, and got a bit scared ;-)

**Comment by inducer** [comment]
Good point. 670318fa4db8e687f3b76d6dddb6ed1dd4b698d6 (LMK if unclear)

FWIW, I ran the script earlier today, so this should now be applied.
