### ISSUE TITLE
nvidia-smi doesn't work anymore on koelsch

### ISSUE THREAD

**Issue by isuruf** [illinois-scicomp/machine-shop-maintenance#60]
```
idf2@koelsch:~$ nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
```

**Comment by isuruf** [comment]
Works on porter though

**Comment by isuruf** [comment]
According to https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch, a reboot might help.

**Comment by inducer** [comment]
Rebooted, should be fixed when it comes back. Should be no more than a couple minutes. LMK if it's still not fixed then.
